class_name TerrainChunkData
extends RefCounted

const CS := TerrainConfig.CHUNK_SIZE
const N := TerrainConfig.VERTS_PER_SIDE
const RANGE := 5.0

var coord: Vector2i
var base_heights := PackedFloat32Array()	# Currently regenerated by terrain_generator.gd, maybe save all heights to prevent changes from altering saved chunks?
var deltas := PackedFloat32Array()			# Player edits
var dirty := false
var biome := 0
var manifest: ChunkManifest = null

func _init(p_coord: Vector2i) -> void:
	coord = p_coord
	base_heights.resize(N * N)
	deltas.resize(N * N)

func generate_base(gen: TerrainGenerator) -> void:
	var gx0 := coord.x * CS
	var gz0 := coord.y * CS
	for z in N:
		for x in N:
			base_heights[z * N + x] = gen.get_base_height(gx0 + x, gz0 + z)

func get_height(x: int, z: int) -> float:
	var i := z * N + x
	return base_heights[i] + deltas[i]

func add_delta(x: int, z: int, amount: float) -> void:
	var i := z * N + x
	deltas[i] = clampf(deltas[i] + amount, -RANGE, RANGE)
	dirty = true

func has_edits() -> bool:
	for d in deltas:
		if d != 0.0:
			return true
	return false

# Bilinear height at a fractional LOCAL position, x/z in [0, CS].
func get_height_interpolated(lx: float, lz: float) -> float:
	var x0 := clampi(floori(lx), 0, N - 2)
	var z0 := clampi(floori(lz), 0, N - 2)
	var fx := lx - x0
	var fz := lz - z0
	var h00 := get_height(x0, z0)
	var h10 := get_height(x0 + 1, z0)
	var h01 := get_height(x0, z0 + 1)
	var h11 := get_height(x0 + 1, z0 + 1)
	return lerp(lerp(h00, h10, fx), lerp(h01, h11, fx), fz)
	
func get_normal_interpolated(lx: float, lz: float, sampler: Callable, gx0: int, gz0: int) -> Vector3:
	var wx := gx0 + lx
	var wz := gz0 + lz
	var hL: float = sampler.call(floori(wx - 1), floori(wz))
	var hR: float = sampler.call(floori(wx + 1), floori(wz))
	var hD: float = sampler.call(floori(wx), floori(wz - 1))
	var hU: float = sampler.call(floori(wx), floori(wz + 1))
	return Vector3(hL - hR, 2.0, hD - hU).normalized()

func set_target_height(x: int, z: int, target: float, factor: float) -> void:
	var i := z * N + x
	var current := base_heights[i] + deltas[i]
	var blended = lerp(current, target, factor)
	deltas[i] = blended - base_heights[i]
	dirty = true

func get_normal_local(lx: float, lz: float) -> Vector3:
	var x0 := clampi(floori(lx), 1, N - 2)
	var z0 := clampi(floori(lz), 1, N - 2)
	var hL := get_height(x0 - 1, z0)
	var hR := get_height(x0 + 1, z0)
	var hD := get_height(x0, z0 - 1)
	var hU := get_height(x0, z0 + 1)
	return Vector3(hL - hR, 2.0, hD - hU).normalized()
