class_name TerrainChunkData
extends RefCounted

const CS := TerrainConfig.CHUNK_SIZE
const N := TerrainConfig.VERTS_PER_SIDE
const RANGE := 5.0

var coord: Vector2i
var base_heights := PackedFloat32Array()	# Currently regenerated by terrain_generator.gd, maybe save all heights to prevent changes from altering saved chunks?
var deltas := PackedFloat32Array()			# Player edits
var dirty := false

func _init(p_coord: Vector2i) -> void:
	coord = p_coord
	base_heights.resize(N * N)
	deltas.resize(N * N)

func generate_base(gen: TerrainGenerator) -> void:
	var gx0 := coord.x * CS
	var gz0 := coord.y * CS
	for z in N:
		for x in N:
			base_heights[z * N + x] = gen.get_base_height(gx0 + x, gz0 + z)

func get_height(x: int, z: int) -> float:
	var i := z * N + x
	return base_heights[i] + deltas[i]

func add_delta(x: int, z: int, amount: float) -> void:
	var i := z * N + x
	deltas[i] = clampf(deltas[i] + amount, -RANGE, RANGE)
	dirty = true

func has_edits() -> bool:
	for d in deltas:
		if d != 0.0:
			return true
	return false
